//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep_Zoologiczny.BazaDanych
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkty
    {
        public int ID_Produktu { get; set; }
        public Nullable<int> ID_Producenta { get; set; }
        public Nullable<int> ID_Kategorii { get; set; }
        public Nullable<int> ID_Podkategorii { get; set; }
        public string Nazwa_produktu { get; set; }
        public decimal Cena { get; set; }
    
        public virtual Kategorie Kategorie { get; set; }
        public virtual Podkategorie Podkategorie { get; set; }
        public virtual Producenci Producenci { get; set; }
    }
}
